### ISSUE TITLE
Public transport links are broken

### ISSUE THREAD

**Issue by ofosos** [nomadenorg/nomads#45]
Since HVV revamped their site, our links are broken. Please fix.

Acceptance criteria:
 - links to HVV site display with proper date, time, start and destination

Reported by @Febell

**Comment by Febell** [comment]
Last URL of my search for the way to nomads:

https://geofox.hvv.de/jsf/home.seam?execute=true&date=08.01.2019&time=19:00&language=de&start=Biedermannplatz%2011&startCity=Hamburg&startType=ADDRESS&destination=Bramfelder%20Chaussee%20361&destinationCity=Hamburg&destinationType=ADDRESS&timeIsDeparture=1&wayBy=train

**Comment by Febell** [comment]
Might we want to delete the start trainstation "Informatikum"? We are no students anymore XD

**Comment by ofosos** [comment]
We could allow to set a cookie and stuff the starting station in there.

**Comment by Febell** [comment]
hm maybe put this into another ticket?

**Comment by Febell** [comment]
We have a ticket for this already: #18
